refresh_rate: 30 seconds

appenders:
  file:
    kind: file
    path: "log/bot.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {l} {m}{n}"
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {l} {m}{n}"

root:
  level: info
  appenders:
    - file
    - stdout
